name: 'Run tests'

runs:
  using: 'composite'

  steps:
    - name: Get code
      uses: actions/checkout@v4
    - name : Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '18'
        cache: 'maven'
    - name: Test
      shell: bash
      run: |
        mvn clean test -P chrome
        if [ $? -ne 0 ]; then
          echo "status=failed" >> $GITHUB_OUTPUT
        else
          echo "status=success" >> $GITHUB_OUTPUT
        fi
    - name: Upload Test Reports
      if: failure () && steps.test-status.outputs.status == 'failed'
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: |
          **/test/surefire-reports
