name: 'Deploy Ingress'

inputs:
  custom_hostname:
    description: 'Custom hostname to be added to /etc/hosts'
    required: true
  ingress_filename:
    description: 'The filename to apply to create the ingress resource'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Get code
      uses: actions/checkout@v4
    - name: Enable Ingress
      shell: bash
      run: minikube addons enable ingress
    - name: Wait for Ingress Controller to Be Ready
      shell: bash
      run: |
        timeout=120
        start_time=$(date +%s)
        while [[ "$(kubectl get deployments -n ingress-nginx ingress-nginx-controller -o=jsonpath='{.status.availableReplicas}')" != "1" ]]; do
        current_time=$(date +%s)
        elapsed_time=$((current_time - start_time))
        if [ "$elapsed_time" -ge "$timeout" ]; then
         echo "Ingress Controller did not become ready within the timeout of $timeout seconds."
         exit 1
        fi
        echo "will sleep"
        sleep 5
        done
    - name: Update /etc/hosts
      shell: bash
      run: |
        kubectl apply -f ${{ inputs.ingress_filename }}
        CUSTOM_HOSTNAME="${{ inputs.custom_hostname }}"
        KUBERNETES_CLUSTER_IP=$(kubectl get nodes -o custom-columns=:status.addresses[0].address --no-headers)
        sudo sh -c "echo '$KUBERNETES_CLUSTER_IP $CUSTOM_HOSTNAME' >> /etc/hosts"
      # Uncomment and modify the following lines if needed
      # for ingress in $(kubectl get ingress -o custom-columns=:metadata.name --no-headers); do
      #   echo "Ingress: $ingress"
      #   kubectl describe ingress $ingress
      #   echo "-----------------------"
      # done
