name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Start Minikube
        id: minikube
        run : minikube start
      - name: Get code
        uses: actions/checkout@v4
      - name: Build Backend Docker Image
        run: |
          eval $(minikube -p minikube docker-env)
          cd backend-api
          docker build -t dev.local/app-backend-api:v1 .
          cd ../frontend
          docker build -t dev.local/app-frontend:v2 .
          minikube image ls --format table
      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic my-secret \
          --from-literal=DATABASE_HOST="$GITHUB_SECRET_DATABASE_HOST" \
          --from-literal=DATABASE_NAME="$GITHUB_SECRET_DATABASE_NAME" \
          --from-literal=DATABASE_PWD="$GITHUB_SECRET_DATABASE_PWD" \
          --from-literal=DATABASE_USER="$GITHUB_SECRET_DATABASE_USER"
        env:
          GITHUB_SECRET_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          GITHUB_SECRET_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          GITHUB_SECRET_DATABASE_PWD: ${{ secrets.DATABASE_PWD }}
          GITHUB_SECRET_DATABASE_USER: ${{ secrets.DATABASE_USER }}
      - name: Create Kubernetes Config
        run: |
          kubectl create configmap my-config-map --from-literal=REACT_APP_BACKEND_HOST=$GITHUB_CONFIG_REACT_APP_BACKEND_HOST
        env:
          GITHUB_CONFIG_REACT_APP_BACKEND_HOST: ${{ vars.REACT_APP_BACKEND_HOST }}
      - name: Deploy PostgreSQL
        uses: ./.github/actions/setup-db
        with:
          postgress_filename: postgres-deployment.yaml
          db_name: mydb
          sql_filename: create-table.sql
      - name : Deploy Backend Service
        run : |
          kubectl apply -f backend-api-deployment.yaml
      - name : Deploy FrontEnd
        run : |
          kubectl apply -f frontend-deployment.yaml
      - name: Print logs
        run: |
          sleep 5
          kubectl logs -l app=backend
          kubectl logs -l app=frontend
      - name: Deploy Ingress
        uses: ./.github/actions/deploy-ingress
        with:
          custom_hostname: mytestapp.com
          ingress_filename: ingress.yaml
      - name: Tests
        uses: ./.github/actions/run-mvn-tests


 
