name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t gh-flask-app:v1 .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Start Minikube
        id: minikube
        run : minikube start
      - name: Check Minikube Status
        run: minikube status
      - name: Get Kubernetes Nodes
        run: kubectl get nodes
      - name: Enable Ingress
        run: minikube addons enable ingress
      - name: Wait for Ingress Controller to Be Ready
        run: |
          timeout=120
          start_time=$(date +%s)
          while [[ "$(kubectl get deployments -n ingress-nginx ingress-nginx-controller -o=jsonpath='{.status.availableReplicas}')" == "0" ]]; do
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ "$elapsed_time" -ge "$timeout" ]; then
           echo "Ingress Controller did not become ready within the timeout of $timeout seconds."
           exit 1
          fi
          echo "will sleep"
          sleep 5
          done
      - name: Get code
        uses: actions/checkout@v4
      - name : Deploy web server
        run : kubectl apply -f webserver.yaml
      #- name : sleep
      #  run : sleep 120
      - name : Plug Ingress
        run : kubectl apply -f ingress.yaml
