name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Build
        run: |
          docker build -t gh-flask-app:v1 .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@master
      - name: Check Minikube Status
        run: minikube status
      - name: Get Kubernetes Nodes
        run: kubectl get nodes
      - name: Enable Ingress
        run: minikube addons enable ingress
      - name: Wait for Ingress Controller Pods
        run: kubectl wait --for=condition=available deployment/ingress-nginx-controller -n ingress-nginx --timeout=120s
      - name: Wait for Ingress Controller Admission Webhook
        run: kubectl wait --for=condition=available deployment/ingress-nginx-admission-create -n ingress-nginx --timeout=120s
      - name: Get code
        uses: actions/checkout@v4
      - name : Deploy web server
        run : kubectl apply -f webserver.yaml
      #- name : sleep
      #  run : sleep 120
      - name : Plug Ingress
        run : kubectl apply -f ingress.yaml
