name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # - name: Login to Docker Hub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build
        run: |
          docker build -t gh-flask-app:v1 .
      #   docker tag flask-app amanmahajan26/flask-app

      #- name: Push
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: amanmahajan26/flask-app:latest
  - name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Start Minikube
        run: minikube start
      - name: Check Minikube Status
        run: minikube status
      - name: Get Kubernetes Nodes
        run: kubectl get nodes

