name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Start Minikube
        id: minikube
        run : minikube start
      - name: Check Minikube Status
        run: minikube status
      - name: Get Kubernetes Nodes
        run: kubectl get nodes
      - name: Enable Ingress
        run: minikube addons enable ingress
      - name: Wait for Ingress Controller to Be Ready
        run: |
          timeout=120
          start_time=$(date +%s)
          while [[ "$(kubectl get deployments -n ingress-nginx ingress-nginx-controller -o=jsonpath='{.status.availableReplicas}')" != "1" ]]; do
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ "$elapsed_time" -ge "$timeout" ]; then
           echo "Ingress Controller did not become ready within the timeout of $timeout seconds."
           exit 1
          fi
          echo "will sleep"
          sleep 5
          done
      - name: Get code
        uses: actions/checkout@v4
      - name: Build Backend Docker Image
        run: |
          eval $(minikube -p minikube docker-env)
          cd backend-api
          docker build -t dev.local/app-backend-api:v1 .
          cd ../frontend
          docker build -t dev.local/app-frontend:v2 .
          minikube image ls --format table
      - name: Create Kubernetes Secret
        run: |
          kubectl create secret generic my-secret \
          --from-literal=DATABASE_HOST="$GITHUB_SECRET_DATABASE_HOST" \
          --from-literal=DATABASE_NAME="$GITHUB_SECRET_DATABASE_NAME" \
          --from-literal=DATABASE_PWD="$GITHUB_SECRET_DATABASE_PWD" \
          --from-literal=DATABASE_USER="$GITHUB_SECRET_DATABASE_USER"
        env:
          GITHUB_SECRET_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          GITHUB_SECRET_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          GITHUB_SECRET_DATABASE_PWD: ${{ secrets.DATABASE_PWD }}
          GITHUB_SECRET_DATABASE_USER: ${{ secrets.DATABASE_USER }}
      - name: Create Kubernetes Config
        run: |
          kubectl create configmap my-config-map --from-literal=REACT_APP_BACKEND_HOST=$GITHUB_CONFIG_REACT_APP_BACKEND_HOST
        env:
          GITHUB_CONFIG_REACT_APP_BACKEND_HOST: ${{ vars.REACT_APP_BACKEND_HOST }}

      - name: Deploy PostgreSQL to Minikube
        run: |
          kubectl apply -f postgres-deployment.yaml
      - name: Wait for PostgreSQL to be ready
        run: |
          until kubectl get pods | grep postgresql | grep "1/1" | grep "Running"; do
            echo "Waiting for PostgreSQL to start..."
            sleep 5
          done
      - name: Execute SQL Statement
        run: |
          kubectl cp create-table.sql $(kubectl get pods | grep postgresql | awk '{print $1}'):/create-table.sql
          kubectl exec $(kubectl get pods | grep postgresql | awk '{print $1}') -- psql -U postgres -d mydb -f /create-table.sql
      - name : Deploy Backend Service
        run : |
          kubectl apply -f backend-api-deployment.yaml
      - name : Deploy FrontEnd
        run : |
          kubectl apply -f frontend-deployment.yaml
      - name: Print logs
        run: |
          sleep 5
          kubectl logs -l app=backend
          kubectl logs -l app=frontend
      #- name : Plug Ingress
      #  run : |
      #    kubectl apply -f ingress.yaml
      #    CUSTOM_HOSTNAME="mytestapp.com"
      #    KUBERNETES_CLUSTER_IP=$(kubectl get nodes -o custom-columns=:status.addresses[0].address --no-headers)
      #    sudo sh -c "echo '$KUBERNETES_CLUSTER_IP $CUSTOM_HOSTNAME' >> /etc/hosts"
      #    # for ingress in $(kubectl get ingress -o custom-columns=:metadata.name --no-headers); do
      #    #  echo "Ingress: $ingress"
      #    #  kubectl describe ingress $ingress
      #    #  echo "-----------------------"
      #    # done
      - name: Deploy Ingress
        uses: ./.github/actions/deploy-ingress
        with:
          custom_hostname: mytestapp.com
          ingress_filename: ingress.yaml
      - name: Tests
        uses: ./.github/actions/run-mvn-tests

      #- name : Test
      #  run : |
      #      mvn clean test -P chrome
      #      if [ $? -ne 0 ]; then
      #        echo "failed" >> test-status.txt
      #      else
      #        echo "success" >> test-status.txt
      #      fi
      #- name: Set Test Status
      #  id: test-status
      #  run: echo ::set-output name=status::$(cat test-status.txt)
      #- name: Upload Test Reports
      #  uses: actions/upload-artifact@v2
      #  if: steps.test-status.outputs.status == 'failed'
      #  with:
      #    name: test-report
      #    path: |
      #      **/test/surefire-reports
 
